### ISSUE TITLE
Fix: Assert always passes

### ISSUE THREAD

**Issue by nicolevanderhoeven** [flood-io/cli#12]
I tried using Assert as per the generated test.ts file as follows: assert(true, 'Hippopotamus') . It looks like this doesn't fail the test step despite the fact that the page I'm running it against doesn't have "hippopotamus" in its source.

**Comment by ivanvanderbyl** [comment]
I don't think this is an issue: Assert takes a predicate as the first argument and an optional message as the second argument. The predicate isn't supplied by assert itself, all it does it evaluate the truthfulness of the predicate and raise an error otherwise.

So in this example: `assert(true)` will always pass, just as `assert(false)` will always fail.
